community:
  - Faculty Member, 2014 Geophysical Fluid Dynamics Summer School,
      Woods Hole Oceanographic Institution, Woods Hole, MA
  - Session Convener, The Southern Ocean and Its Role in the Climate System;
      Observations and Modeling of Physical and Biogeochemical Processes,
      2014 Ocean Sciences Meeting, Honolulu, HI
  - Member, American Geophysical Union
  - Member, European Geophysical Union
  - Member, American Meteorological Society
  - Reviewer for Journal of Physical Oceanography
  - Reviewer for Journal of Geophysical Research Oceans
  - Reviewer for Geophysical Research Letters
  - Reviewer for Ocean Modelling
  - Reviewer for Nature Communications
  - Reviewer for National Science Foundation

university:
  - DEES Curriculum Committee (2016)
  - DEES Broad Search Committee (2016)
  - DEES Cryosphere Search Committee (2015)
  - Yeti High Performance Computing Executive Committe (2015-2016)
  - LDEO Real Time Earth Initiative Committee
  - Center for Climate and Life Board Member 
