community:
  - "Session Chair, Transport and Coherent Structures: New and Traditional
     Approaches for Studying Ocean Stirring and Mixing,
     2018 Ocean Sciences Meetings, Portland, OR"
  - Faculty Member, 2014 Geophysical Fluid Dynamics Summer School,
      Woods Hole Oceanographic Institution, Woods Hole, MA
  - Session Chair, The Southern Ocean and Its Role in the Climate System;
      Observations and Modeling of Physical and Biogeochemical Processes,
      2014 Ocean Sciences Meeting, Honolulu, HI
  - Member, EarthCube Science Committee
  - Member, American Geophysical Union
  - Member, European Geophysical Union
  - Member, American Meteorological Society
  - Reviewer for Journal of Physical Oceanography
  - Reviewer for Journal of Geophysical Research Oceans
  - Reviewer for Geophysical Research Letters
  - Reviewer for Ocean Modelling
  - Reviewer for Nature Communications
  - Reviewer for National Science Foundation

university:
  - DEES Curriculum Committee (2016)
  - DEES Broad Search Committee (2016)
  - DEES Cryosphere Search Committee (2015)
  - Yeti High Performance Computing Executive Committe (2015-2016)
  - Leader, LDEO Real Time Earth Strategic Initiative
  - Board Member, Center for Climate and Life
  - Member, Columbia Data Science Institute Working Group on Frontiers in
      Computing Systems
